export const seoTerms = [
  "real estate",
  "realtor",
  "homes for sale",
  "buy home",
  "sell house",
  "property listings",
  "home valuation",
  "real estate agent",
  "realty services",
  "real estate market",
  "luxury homes",
  "affordable homes",
  "investment property",
  "first-time homebuyer",
  "property sale",
  "real estate consultant",
  "local realtor",
  "property search",
  "real estate listings",
  "real estate california",
  "real estate lancaster",
  "real estate palmdale",
  "real estate los angeles",
  "real estate santa clarita",
]
